[profile.default]
src = "evm/src"
out = "evm/out"
libs = ["evm/lib"]
test = "evm/test"
script = "evm/script"
solc_version = "0.8.26"
optimizer = true
optimizer_runs = 200
via_ir = false

[profile.ci]
fuzz = { runs = 10000 }
invariant = { runs = 1000 }

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true
int_types = "long"

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }
